name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    # checkout code from repo
    - name: Checkout code
      uses: actions/checkout@v1
      
    # setup nuget
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    # restore packages from nuget
    - name: Restore packages with nuget
      run: nuget restore ./Source/Tailwind.Traders.Web.sln
    
    # setup msbuild and put it in the path
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    # build solution
    - name: build solution
      run: msbuild ./Source/Tailwind.Traders.Web.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="%GITHUB_WORKSPACE%\staging"'
        
    # find zip file
    - name: find zip
      run: |
        pwd
        ls
        cd staging
        ls
        pwd
    
    # upload build artifact
    - name: publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: staging
