name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    # checkout code from repo
    - name: Checkout code
      uses: actions/checkout@v1
      
    # setup nuget
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    # restore packages from nuget
    - name: Restore packages with nuget
      run: nuget restore ./Source/Tailwind.Traders.Web.sln
    
    # setup msbuild and put it in the path
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    # build solution
    #- name: Build solution
    #  run: msbuild ./Source/Tailwind.Traders.Web.sln /nologo /nr:false /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="16.0" /p:PackageLocation="%GITHUB_WORKSPACE%\staging"
    
    # copy zip to stabing
    - name: Build solution
      run: copy .\Deploy\Tailwind.Traders.Web.zip .\Tailwind.Traders.Web.zip
    
    # find zip file
    - name: Find zip
      run: |
        echo pwd
        pwd
        echo ls
        ls
        echo cd Deploy
        cd Deploy
        echo pwd
        pwd
        echo ls
        ls
    
    # upload build artifact
    - name: Publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: Deploy
        path: staging

  provisionAndDeploy:
    needs: [build] 
    runs-on: windows-latest
    steps:
      
      # download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: webapp
          
      # find zip file
      - name: Find zip
        run: |
          echo pwd
          pwd
          echo ls
          ls
          echo cd webapp
          cd webapp
          echo pwd
          pwd
          echo ls
          ls
                    
      # Deploy build artifact to Azure App Service
      #- name: Publish website to Azure App Service
      #  uses: azure/webapps-deploy@v1
      #  with:
      #    app-name: abeltailwindstaging  # Replace with your app name
      #    package: webapp  # Specify the folder or file to deploy
      #    publish-profile: ${{ secrets.PUBLISH_PROFILE }}  # Replace with the name of your publish profile
          
      # Deploy build artifact to Azure App Service
      - name: Publish website to Azure App Service
        uses: azure/appservice-actions/webapp@master
        with:
          app-name: abeltailwindstaging  # Replace with your app name
          package: webapp\Tailwind.Traders.Web.zip  # Specify the folder or file to deploy
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}  # Replace with the name of your publish profile
